version: '3.8'

services:
  # client:
  #   build: ./client
  #   ports:
  #     - '8080:8080'

  # api:
  #   container_name: test-api
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3001:3000
  #    volumes:
  #      - ./:/usr/src/app
  #     - dependencies:/usr/src/app/node_modules/
  #   command: yarn dev

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'auth_starter'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
