version: '3.8'

services:
  # backend:
  #   build: ./server
  #   container_name: node-backend
  #   restart: unless-stopped
  #   ports:
  #     - '3000:3000'
  #   networks:
  #     - app-network

  # frontend:
  #   build: ./client
  #   container_name: react-frontend
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #   networks:
  #     - app-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'auth_starter'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - app-network

volumes:
  my-db:

networks:
  app-network:
    driver: bridge
